# Generated by Django 2.2 on 2019-05-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190504_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
