# Generated by Django 2.2 on 2019-05-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190504_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='caption4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='caption5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='caption6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='caption7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='caption8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='caption9',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image10',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image4',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image5',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image6',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image7',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image8',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image9',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
